%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/lizzy/Principal.Component.Pursuit/Data/nhanes_50.csv
%
% Auto-generated by MATLAB on 13-Mar-2021 12:52:40

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["PCB074", "PCB099", "PCB118", "PCB138", "PCB153", "PCB156", "PCB170", "PCB180", "PCB187", "D03", "D05", "D07", "F03", "F04", "F05", "F08", "PCB126", "PCB169", "PCB194", "PCB196", "PCB199"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
nhanes50 = table2array(readtable("/Users/lizzy/Principal.Component.Pursuit/Data/nhanes_50.csv", opts));

% Import the data
nhanes50_lod = table2array(readtable("/Users/lizzy/Principal.Component.Pursuit/Data/nhanes_50_lods.csv", opts));

%% Clear temporary variables
clear opts

[m,p] = size(nhanes50);
lambda = 1/sqrt(m); 
mu = sqrt(p/(2*log(m*p)));

[L,S] = root_pcp_with_nan_nonnegL_LOD(nhanes50, lambda, mu, nhanes50_lod); 
norm(L, "Fro")
norm(S, "Fro")
