---
title: "PCP -- vary $\\lambda$ and $\\mu$"
author: "Lizzy Gibson"
date: "8/18/2020"
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 4
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
options(scipen = 999)
library(tidyverse)
library(janitor)
library(reshape2)
library(matconv)
library(ggcorrplot)
library(ggfortify)  
library(gridExtra)
library(factoextra)
library(Matrix)
library(rlist)
library(ggrepel)
library(broom)
library(R.matlab)
library(pcpr)
```

# Boston data

## Read from HPC
```{r read}
boston_out <- tibble()

for (i in 1:223) {
  load(here::here(paste0("/HPC_PCP/R_out/boston_param/boston_param_out_", i, ".RDA")))
  boston_out[i,1:8] <- all_out
}

for (i in 225:360) {
  load(here::here(paste0("/HPC_PCP/R_out/boston_param/boston_param_out_", i, ".RDA")))
  boston_out[i-1,1:8] <- all_out
}

for (i in 362:420) {
  load(here::here(paste0("/HPC_PCP/R_out/boston_param/boston_param_out_", i, ".RDA")))
  boston_out[i-2,1:8] <- all_out
}

boston_out <- boston_out %>% 
  mutate_at(vars(1:2), as.factor)

# save(boston_out, file = "boston_param_out_all.RDA")
# load("boston_param_out_all.RDA")
```

```{r}
# Read air pollution data
mixture <- readMat(here::here("Data/mixtures_data.mat"))

mix <- as.data.frame(mixture) %>% as_tibble() %>% 
  select(Al, As, Ba, bc, Br, Ca, Cl,
         Cr, Cu, Fe, K,  Mn,  Ni,  Pb,  S,  Se,  Si,
         Ti,  V, Zn) %>% 
  drop_na(.) %>% 
  as.matrix(.)

nn <- nrow(mix)
mm <- ncol(mix)

#This is the default
lam_mix = 1/sqrt(nn)
mu_mix = sqrt(mm/(2*log(nn*mm)))
```

```{r}
default <- boston_out %>%
  filter(lam_values == 0.02 & mu_values == 0.96)
```

## Low Rank Matrix

Examine how rank of low rank matrix changes with varying $\lambda$ and $\mu$.

All ranks:
```{r rank_ml}
boston_out %>% pull(rank_L) %>% summary()

boston_out %>% 
  ggplot(aes(x = mu_values, y = lam_values)) +
  geom_tile(aes(fill = rank_L), color = "white") +
    geom_tile(aes(fill = rank_L), color = "black", size = 0.75,
              data = default) +
  scale_fill_gradientn(colours = rainbow(10), 
                      na.value = "transparent") +
  theme_classic() + labs(fill = "Rank", 
                    y = expression(lambda),
                    x = expression(mu),
                    title = "Low rank matrix rank") +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 70, hjust = 1))
```

## Sparse Matrix

Examine how sparsity of sparse matrix changes with varying $\lambda$ and $\mu$.

Density:
```{r plot_sparse}
boston_out %>% pull(density_S) %>% summary()

boston_out %>%
  ggplot(aes(y = lam_values, x = mu_values)) + 
  geom_tile(aes(fill = density_S), color = "white") +
      geom_tile(aes(fill = density_S), color = "black", size = 0.75,
              data = default) +
  scale_fill_gradientn(colours = rainbow(10), 
                      na.value = "transparent") +
  theme_bw() + labs(fill = "Density", 
                    y = expression(lambda),
                    x = expression(mu),
                    title = "Sparse matrix density") +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 70, hjust = 1))
```

## Error

Don't know the *true L* here, so compare L + S to original data.

Relative error:
```{r plot_err}
boston_out %>% pull(total_rel_error) %>% summary()

boston_out %>% 
  ggplot(aes(x = mu_values, y = lam_values)) +
  geom_tile(aes(fill = total_rel_error), color = "white") +
        geom_tile(aes(fill = total_rel_error), color = "black", size = 0.75,
              data = default) +
  scale_fill_gradientn(colours = rainbow(10), 
                      na.value = "transparent") +
  theme_classic() + labs(fill = "RMSE", 
                    y = expression(lambda),
                    x = expression(mu),
                    title = "Relative error") +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 70, hjust = 1))
```

## Default values

```{r, include=FALSE, cache=TRUE}
mixture <- pcp_lod(mix, lam_mix, mu_mix, 0)
```

```{r}
L <- mixture$L
S <- mixture$S
sv_diag <- svd(L)$d # singular values on new low rank matrix
rank_L <- rankMatrix(L)
```

Rank of L:
```{r}
rank_L
```

Density of S:
```{r}
cells <- nn*mm
as_tibble(S) %>% 
    pivot_longer(Al:Zn) %>% 
    mutate(binary = ifelse(value == 0, 0, 1)) %>% 
    summarize(density = sum(binary)/cells) %>% 
    pull(density)
```

