---
title: "NMF vs SVD"
author: "Lizzy Gibson"
date: "8/9/2019"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
require("knitr")
opts_knit$set(root.dir = "../../")
opts_chunk$set(echo = TRUE)
options(scipen = 999)
library(R.matlab)
library(tidyverse)
library(gridExtra)
library(Matrix)
library(NMF)
```

## Data

* 20 air pollution species
* 2,478 days (~6.7 years)

## Read MATLAB Output

Run PCP on separate datasets in MATLAB, load results L and S matrices from file.

*Low Rank Matrices*
```{r}
L_lod0 <- readMat("./Below_LOD/MATLAB/LOD_demo_output/lowrank_lod0.mat") %>% as.data.frame() %>% as_tibble() %>% as.matrix()
L_lod10 <- readMat("./Below_LOD/MATLAB/LOD_demo_output/lowrank_lod10.mat") %>% as.data.frame() %>% as_tibble() %>% as.matrix()
L_lod20 <- readMat("./Below_LOD/MATLAB/LOD_demo_output/lowrank_lod20.mat") %>% as.data.frame() %>% as_tibble() %>% as.matrix()
L_lod30 <- readMat("./Below_LOD/MATLAB/LOD_demo_output/lowrank_lod30.mat") %>% as.data.frame() %>% as_tibble() %>% as.matrix()
L_lod40 <- readMat("./Below_LOD/MATLAB/LOD_demo_output/lowrank_lod40.mat") %>% as.data.frame() %>% as_tibble() %>% as.matrix()
L_lod50 <- readMat("./Below_LOD/MATLAB/LOD_demo_output/lowrank_lod50.mat") %>% as.data.frame() %>% as_tibble() %>% as.matrix()
```

## Compare NMF to SVD Solution

### SVD results of L Matrix

```{r}
plot(svd(L_lod0)$d)

# Extract right singular vectors from each low rank solution matrix
V_lod0  <- svd(L_lod0)$v[,1:5]
V_lod10 <- svd(L_lod10)$v[,1:5]
V_lod20 <- svd(L_lod20)$v[,1:5]
V_lod30 <- svd(L_lod30)$v[,1:5]
V_lod40 <- svd(L_lod40)$v[,1:5]
V_lod50 <- svd(L_lod50)$v[,1:5]

V_diff <- as_tibble(cbind(lod0 =norm((V_lod0 - V_lod0), type = "F")/norm((V_lod0), type = "F"),
      lod10 =norm((V_lod10 - V_lod0), type = "F")/norm((V_lod0), type = "F"),
      lod20 =norm((V_lod20 - V_lod0), type = "F")/norm((V_lod0), type = "F"),
      lod30 =norm((V_lod30 - V_lod0), type = "F")/norm((V_lod0), type = "F"),
      lod40 =norm((V_lod40 - V_lod0), type = "F")/norm((V_lod0), type = "F"),
      lod50 =norm((V_lod50 - V_lod0), type = "F")/norm((V_lod0), type = "F"))) %>% 
  gather(percent_blod, norm)

V_diff %>% ggplot(aes(x = percent_blod, y = norm)) + 
  geom_point() + geom_path(aes(group = 1)) + theme_bw() +
  labs(x = "Percent Below LOD", 
       y = "Relative Error in Low-Rank Solution Singular Vectors\n(norm(SV - SV_lod0) / norm(SV_lod0))")
```

### NMF results of L Matrix

```{r}
nmf(L_lod0, 5)

# Extract right singular vectors from each low rank solution matrix
V_lod0  <- svd(L_lod0)$v[,1:5]
V_lod10 <- svd(L_lod10)$v[,1:5]
V_lod20 <- svd(L_lod20)$v[,1:5]
V_lod30 <- svd(L_lod30)$v[,1:5]
V_lod40 <- svd(L_lod40)$v[,1:5]
V_lod50 <- svd(L_lod50)$v[,1:5]

V_diff <- as_tibble(cbind(lod0 =norm((V_lod0 - V_lod0), type = "F")/norm((V_lod0), type = "F"),
      lod10 =norm((V_lod10 - V_lod0), type = "F")/norm((V_lod0), type = "F"),
      lod20 =norm((V_lod20 - V_lod0), type = "F")/norm((V_lod0), type = "F"),
      lod30 =norm((V_lod30 - V_lod0), type = "F")/norm((V_lod0), type = "F"),
      lod40 =norm((V_lod40 - V_lod0), type = "F")/norm((V_lod0), type = "F"),
      lod50 =norm((V_lod50 - V_lod0), type = "F")/norm((V_lod0), type = "F"))) %>% 
  gather(percent_blod, norm)

V_diff %>% ggplot(aes(x = percent_blod, y = norm)) + 
  geom_point() + geom_path(aes(group = 1)) + theme_bw() +
  labs(x = "Percent Below LOD", 
       y = "Relative Error in Low-Rank Solution Singular Vectors\n(norm(SV - SV_lod0) / norm(SV_lod0))")
```

## Visualize



```{r}
as_tibble(V_lod0) %>% 
  mutate(id = c("Al", "As", "Ba", "bc", "Br", "Ca", "Cl",
                "Cr", "Cu", "Fe", "K",  "Mn",  "Ni",  "Pb",  "S",  "Se",  "Si",
                "Ti",  "V", "Zn")) %>% 
  select(id, everything()) %>% 
  gather(key = singular_vector, value = magnitude, V1:V5) %>%
  ggplot(aes(x = id, y = magnitude)) + geom_point(color = "blue") + 
  geom_segment(aes(xend = id, yend = 0), color = "blue") +
  facet_grid(. ~ singular_vector) +
  geom_hline(yintercept = 0, linetype = "dashed", 
             color = "red") +
  theme_bw() + labs(x = "", y = "Magnitude", title = "First 5 right singular vectors of V")

```

